# Generated by Django 4.2.3 on 2023-08-13 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projeto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='name',
            new_name='nome',
        ),
    ]
